### PR TITLE
Person metadata

### PR DESCRIPTION
**Pull request by alyxrossetti**

### CODE REVIEW

**Comment by rit** [comment]
@alyxrossetti  Please read my comments/checklist here: https://trello.com/c/3ep68Smp

**Comment by alyxrossetti** [comment]
Thanks, @rit - changes made and ready for review

**Comment by rit** [comment]
@alyxrossetti the GettyEllipsis component should be completely isolated: it does not need to communicate with its parent and its parent doesn't care about its "more/less" state. So we don't need to pass the 'handler.' With that, `props` should be replaced with `data`.  Also the GettyEllipsis should inspect the length of the description and only shows the 'READ MORE' when it's longer than a certain length, say 80 words?

**Comment by alyxrossetti** [comment]
@rit Good point, I separated `getty-ellipsis` from the parent. Currently READ MORE is shown when there are more than 3 lines of text. This seems like a better option to me than counting words...especially when thinking about smaller screens.

**Comment by rit** [comment]
@alyxrossetti using line-height in stead of word count works for me.

**Comment by rit** [comment]
@alyxrossetti Nice!!! After removing the noise, the code duplicate seems to reveal itself. We can further improve clean this:
```
diff --git a/gpi/frontend/web/src/ui/components/getty-ellipsis.vue b/gpi/frontend/web/src/ui/components/getty-ellipsis.vue
index c755490..59ec55c 100644
--- a/gpi/frontend/web/src/ui/components/getty-ellipsis.vue
+++ b/gpi/frontend/web/src/ui/components/getty-ellipsis.vue
@@ -5,19 +5,11 @@
       class="pi-slot-wrapper is-size-7">
       <slot/>
     </div>
-    <div
-      v-if="showContent">
+    <div>
       <a
         class="is-uppercase is-size-7"
         href="#"
-        @click.prevent="toggleContent()">Show Less</a>
-    </div>
-    <div
-      v-else>
-      <a
-        class="is-uppercase is-size-7"
-        href="#"
-        @click.prevent="toggleContent()">Read More...</a>
+        @click.prevent="toggleContent()">{{ moreOrLess() }}</a>
     </div>
   </div>
 </template>
@@ -34,6 +26,9 @@ export default {
     toggleContent () {
       this.showContent = !this.showContent
     },
+    moreOrLess () {
+      return this.showContent ? 'Show Less' : 'Read More...'
+    },
   },
 }
 </script>
```
what do you think?

**Comment by alyxrossetti** [comment]
@rit Looks great!

**Pull request merged**
