### PR TITLE
Resource type

### PR DESCRIPTION
**Pull request by alyxrossetti**

### CODE REVIEW

**Comment by alyxrossetti** [comment]
@rit tests added and ready for review

**Comment by alyxrossetti** [comment]
@rit conflicts fixed and small css tweaks pushed

**Comment by rit** [comment]
@alyxrossetti I've introduced a `ResourceType` model in the `iso/models` folder. Let's review this together in person tomorrow.

**Comment by alyxrossetti** [comment]
@rit I just looked it over and it makes sense - but still happy to discuss in person

**Pull request merged**
